### PR TITLE
Created a command just for dan

### PR DESCRIPTION
**Pull request by Jonfirexbox**
Just thought i might add something, i feel like it needed a new command for dan ;)

### CODE REVIEW

**Comment by itzJOHv** [comment]
lol

**Comment by Hadimhz** [comment]
love the effort, but kind of a useless command.

**Comment by Jonfirexbox** [comment]
ok

**Comment by Hadimhz** [comment]
> eh ive seen things more useless

obviously, you've looked in at a mirror before.

**Comment by Microwave-6443** [comment]
> > eh ive seen things more useless
> 
> obviously, you've looked in at a mirror before.

bruh

**Pull request closed without merging**
