### PR TITLE
Resolving create command.

### PR DESCRIPTION
**Pull request by DIBSTERYT**
Alright, I think I finally figured out the server creation command, this should allow DBH!server create list to show the list, while also making sure all previous changes to the create command will work like usual.

### CODE REVIEW

**Comment by itzJOHv** [comment]
why not just `return await message.channel.send(...)`

**Comment by avixityyt** [comment]
> why not just `return await message.channel.send(...)`

at the end it still does the same thing , so doesn't matter that much.

**Comment by DIBSTERYT** [comment]
@avixityyt Yeah same exact thing just copied the code from the one from above and change it so it would work for list. 👌

**Comment by avixityyt** [comment]
> @avixityyt Yeah same exact thing just copied the code from the one from above and change it so it would work for list. 👌

i know , i was replying to the other users comment , but good that you made changes.

**Comment by DIBSTERYT** [comment]
Yep now all I have to do is wait for Dan or Freddie to merge it.

**Review by danielpmc — APPROVED** [review]

**Pull request merged**
