### PR TITLE
you need to require chalk to use it

### PR DESCRIPTION
**Pull request by SirEpiclyAmazing**

### CODE REVIEW

**Comment by Xcyth** [comment]
this is the 2nd most useless pr ive ever seen
1st was by that dude dragonizedpizza

**Comment by Darker-Ink** [comment]
*cough take a look at line 34 in index.js*

**Comment by itzJOHv** [comment]
y are ppl making prs with no sense

just better go play minecraft and dont use github

**Comment by Sliden101** [comment]
> y are ppl making prs with no sense
> 
> just better go play minecraft and dont use github

cus they can

**Comment by itzJOHv** [comment]
> > y are ppl making prs with no sense
> > 
> > just better go play minecraft and dont use github
> 
> cus they can

stupid answer ngl

**Comment by Sliden101** [comment]
> > > y are ppl making prs with no sense
> > > just better go play minecraft and dont use github
> > 
> > 
> > cus they can
> 
> stupid answer ngl

still an answer ¯\_(ツ)_/¯

**Review by itzJOHv — CHANGES_REQUESTED** [review]
w h y

**Comment by itzJOHv** [comment]
kekw

**Pull request closed without merging**
