### PR TITLE
Made so you can give people your donator servers

### PR DESCRIPTION
**Pull request by ItzArmic**

### CODE REVIEW

**Comment by itzJOHv** [comment]
u can rename ur PR lmao #103

**Comment by freddierick** [comment]
What about sending multiple servers?

Also a confirmation message?

**Comment by AArmic** [comment]
> What about sending multiple servers?
> 
> Also a confirmation message? i.e. you have to confirm you want to send the servers
I could but too lazy someone else do it

**Comment by Hadimhz** [comment]
I am personally against this as it introduce a few security risks and will probably increase the number of servers on donator nodes.
 I'll leave it for @danielpmc to decide

**Pull request closed without merging**
