### PR TITLE
Rewrite Repository

### PR DESCRIPTION
**Pull request by vinc3nz**
I made a repo for rewriting the bot.
This is just because we need to rewrite the bot and I couldn't find a rewrite repo yet.

### CODE REVIEW

**Comment by itzJOHv** [comment]
because it's private and dotto and james are working on it

**Comment by vinc3nz** [comment]
So why is it private if everyone could help?

**Comment by itzJOHv** [comment]
dont ask me that

**Comment by Sliden101** [comment]
actually ye y rewrite private

**Comment by itzJOHv** [comment]
i'd be glad to help rewrite the bot too but i dont even know who i need to contact

**Comment by itzJOHv** [comment]
> actually ye y rewrite private

my guess is because everyone has their own linting and more ppl do the code = more mess the code is.
but why not just make an eslint config for the repo

**Pull request closed without merging**
