### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by Bocon778**

### CODE REVIEW

**Comment by itzJOHv** [comment]
cringe pr but ok

**Review by itzJOHv — APPROVED** [review]
cringe but ok

**Comment by Microwave-6443** [comment]
how is this cringe? literally makes sure no one has trouble when reading it

**Comment by omxpro** [comment]
Hey @danielpmc this pr somehow bugged the create-donator command, now everyone can make servers in donater node. Please fix it before it gets flooded with free users absuing it..

**Comment by omxpro** [comment]
Why did I say this pr? I said it because after this pr it broke **I am not sure** so please don't blame me or go toxic on me

**Comment by Sliden101** [comment]
> Why did I say this pr? I said it because after this pr it broke **I am not sure** so please don't blame me or go toxic on me 

What are you stupid, read the changes

**Pull request merged**
