### PR TITLE
Lets only staff use the snipe command

### PR DESCRIPTION
**Pull request by Xcyth**

### CODE REVIEW

**Comment by FC5570** [comment]
#90

**Comment by AArmic** [comment]
no fuck off

**Comment by bubblejoey** [comment]
yey I got muted

**Comment by NANO-ck** [comment]
Let everyone use it

But we each can only use the command once or twice a day

**Comment by HyptexPvP** [comment]
> Let everyone use it
> 
> But we each can only use the command once or twice a day

How about no?

**Pull request merged**
