### PR TITLE
feat: implement multiple mass mention protection

### PR DESCRIPTION
**Pull request by FC5570**
Bans user if message has more than 20 pings. Temporary implementation until raids stop ~~and the bot gets rewritten~~.

### CODE REVIEW

**Comment by itzJOHv** [comment]
no need to call tostring method if its already in string

**Comment by Luxxy-GF** [comment]
also can i be unmuted

**Review by jeweetzelfWasTaken — CHANGES_REQUESTED** [review]
Isn't it message.mentions.user**s**? And meybe check for members as well, idk if that's needed. Like if they mention someone with <@id> it's a user but with <@!id> it's a member right?

**Comment by FC5570** [comment]
> no need to call tostring method if its already in string

?? toString mentions a user, <@id> 
https://github.com/discordjs/discord.js/blob/stable/src/structures/GuildMember.js#L457

**Comment by Luxxy-GF** [comment]
👍

**Comment by Luxxy-GF** [comment]
👍

**Comment by Luxxy-GF** [comment]
imagine

**Comment by heavennodes** [comment]
no unmutes noobs

**Comment by FC5570** [comment]
Please stop cluttering this with unnecessary comments.

**Comment by HogunWasTaken** [comment]
:cry:
sads

**Comment by itzJOHv** [comment]
> > no need to call tostring method if its already in string
> 
> ?? toString mentions a user, <@id> https://github.com/discordjs/discord.js/blob/stable/src/structures/GuildMember.js#L457

it's already in a string so stringifying it again has no sense

**Pull request merged**
