### PR TITLE
fix: Staff proxy fix

### PR DESCRIPTION
**Pull request by Kyro3400**
Change log:
- Added in all US proxies
- Removed CAProxy and FRProxy from list (Unsure why i kept CA and FR as those aren’t used at all)
- Renamed `getNewKeyDono` to `DonatorProxy` to match what the `server proxy` command has it listed as

Note: Fully edited from Github no VSC so idk if everything is right

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
This could all be merged into one function where you just parse the proxy info when calling it.

**Comment by Kyro3400** [comment]
Yeah that could definitely be worked on, mainly followed how the command looked originally.

Could we also add some labels to this?

**Comment by DEV-DIBSTER** [comment]
Closed as I just addressed this in my latest changes.

**Comment by Kyro3400** [comment]
> Closed as I just addressed this in my latest changes.

Thanks dib!

**Pull request closed without merging**
