### PR TITLE
Update create.js

### PR DESCRIPTION
**Pull request by vinc3nz**
+ Everything now uses `message.reply`
+ Now shows the Discord User to the Account ID
+ Updates the contact panel Admin message

### CODE REVIEW

**Comment by yuansheng1549** [comment]
can you please look at package.json? djs is not even v13

**Comment by Xcyth** [comment]
> can you please look at package.json? djs is not even v13
> 

this doesn't even have v13 code?

**Comment by yuansheng1549** [comment]
> > can you please look at package.json? djs is not even v13
> 
> this doesn't even have v13 code?

i mean it looks ugly with message.reply on djs v12

**Comment by vinc3nz** [comment]
No.

**Comment by Pai-en** [comment]
Lol update code to latest commit pls

**Comment by omxpro** [comment]
> > > can you please look at package.json? djs is not even v13
> > 
> > 
> > this doesn't even have v13 code?
> 
> i mean it looks ugly with message.reply on djs v12

Ye

**Pull request closed without merging**
