### PR TITLE
had to do this man

### PR DESCRIPTION
**Pull request by Dragonizedpizza**
also this code works
and no this is not troll

### CODE REVIEW

**Comment by Xcyth** [comment]
lmaoo u did the exact opposite of the ethics

**Comment by Dragonizedpizza** [comment]
@Xcyth how

**Comment by Xcyth** [comment]
I'll explain later let me sleep now 😪🥱

**Comment by Dragonizedpizza** [comment]
ok tata

**Comment by FC5570** [comment]
how to get banned like steel 101

**Comment by Dragonizedpizza** [comment]
@FC5570 how is this wrong tho

**Comment by Dragonizedpizza** [comment]
forget just dm it to me

**Comment by Dragonizedpizza** [comment]
I feel like I did something wrong ):
this code actually works D:

**Comment by karelkryda** [comment]
Good job...you just reformatted every fucking single file and then make pull request 🤯

**Comment by Dragonizedpizza** [comment]
@karelkryda I made it look cleaner yes

**Comment by Dragonizedpizza** [comment]
was I not supposed to

**Comment by Microwave-6443** [comment]
I understand that some people might have the urge to do this but this is a good way to join the "i did something unnecessary" club

**Comment by karelkryda** [comment]
@Dragonizedpizza but why...it's useless

**Comment by Dragonizedpizza** [comment]
cos... im so bored that I need to

**Comment by Microwave-6443** [comment]
who the heck even has the time to do this? like wtf

**Comment by karelkryda** [comment]
@Microwave-6443 hello 😁

btw yeah...why tf someone do that

**Comment by Microwave-6443** [comment]
lol anyone who does this has WAYYYYY too much time to spend...

**Comment by Dragonizedpizza** [comment]
you save your eyes pain using this dan
just merge it

**Comment by Microwave-6443** [comment]
maybe Raid: Shadow Legends sponsored this

**Comment by Dragonizedpizza** [comment]
what

**Comment by Dragonizedpizza** [comment]
why do fc and xcyth say im gonna get repo banned

**Comment by karelkryda** [comment]
Did you know that if Dan wanted to do it, he could have done it himself a million times?

**Comment by FC5570** [comment]
holy fuck it was a joke bro calm tf down you aren't getting banned

**Comment by Microwave-6443** [comment]
idk... steel did some stupid stuff on this github and dan banned him from it... also the last person who wanted to do this got their pull request denied

**Comment by Dragonizedpizza** [comment]
ok

**Comment by Dragonizedpizza** [comment]
> holy fuck it was a joke bro calm tf down you aren't getting banned

I really didnt care about getting banned doe LMAO

**Comment by Dragonizedpizza** [comment]
my github notifications gone big

**Comment by Dragonizedpizza** [comment]
YO WAIT DOES DBH STILL HAVE THAT EMBED GITHUB WEBHOOK THINGY

**Comment by Microwave-6443** [comment]
> YO WAIT DOES DBH STILL HAVE THAT EMBED GITHUB WEBHOOK THINGY

if you mean the thing that sends github messages into discord chat then yes

**Comment by Dragonizedpizza** [comment]
IF WE SEND ENOUGH MESSAGES WE CAN GET IT DISABLED

**Comment by Dragonizedpizza** [comment]
rather banned from DIscord api

**Comment by FC5570** [comment]
'i really didn't care':
1) you wouldn't have joined with an alt to talk about it in the server because your main was banned.
2) you wouldnt have asked about why you were gonna get banned in your comment a few minutes ago

**Comment by Dragonizedpizza** [comment]
> 'i really didn't care':
> 
> 1. you wouldn't have joined with an alt to talk about it in the server because your main was banned.
> 2. you wouldnt have asked about why you were gonna get banned in your comment a few minutes ago

1. what alt
2. I was curious :facepalm:

**Comment by Microwave-6443** [comment]
bruh... dont attempt to spam it just to get it disabled... thats a good way to get muted in discord and banned from the github

**Comment by Dragonizedpizza** [comment]
ill just do it with an alt :mmLol:

**Comment by Dragonizedpizza** [comment]
jk jk jk

**Comment by Microwave-6443** [comment]
> ill just do it with an alt :mmLol:

your gonna get us all banned...

**Comment by Dragonizedpizza** [comment]
> > ill just do it with an alt :mmLol:
> 
> your gonna get us all banned...

you'll never know if its my alt, its not associated with me
if I let my name contain micro however, they'll consider it your alt :upsidemmLol:

**Comment by Dragonizedpizza** [comment]
but I wont

**Comment by Microwave-6443** [comment]
> > > ill just do it with an alt :mmLol:
> > 
> > 
> > your gonna get us all banned...
> 
> you'll never know if its my alt, its not associated with me
> if I let my name contain micro however, they'll consider it your alt :upsidemmLol:

1. bruh 2. i dont have any alts...

**Comment by Dragonizedpizza** [comment]
ok

**Comment by Dragonizedpizza** [comment]
25 mins till 12

**Comment by Dragonizedpizza** [comment]
also can you persuade Dan to unban me from DBH

**Comment by Microwave-6443** [comment]
you were banned? for what?

**Comment by Dragonizedpizza** [comment]
> you were banned? for what?

I was banned like 9000 years ago
Probably for being toxic and sending memz virus

**Comment by Microwave-6443** [comment]
A human lives for like 100 years, 9000 years ago the internet didn't even exist... 9000 years ago i dont even think the roman empire existed

**Comment by Dragonizedpizza** [comment]
> A human lives for like 100 years, 9000 years ago the internet didn't even exist... 9000 years ago i dont even think the roman empire existed

ok

**Comment by Dragonizedpizza** [comment]
I'm about to watch a movie, any reccomendations?

**Comment by Microwave-6443** [comment]
idk if this would be called a movie but "The Last Kingdom" but heh who cares?

**Pull request closed without merging**
