### PR TITLE
Discord.js v13 rewrite 

### PR DESCRIPTION
**Pull request by fado3669**
a hell

### CODE REVIEW

**Comment by Azuz396** [comment]
Note: in client I Provided all intents, Dan if u dont have enabled the "Guild Presences" and "Guild Members" on Dev Portal Please turn them on in order to start the Client/Bot ;)

**Comment by Azuz396** [comment]
another note: I recommend testing this PR when its ready on DBH Beta bot

**Comment by Darker-Ink** [comment]
imo I suggest waiting until v13 is fully out, they are changing stuff a lot so they could change on thing and it could break the full bot

**Comment by Azuz396** [comment]
thats why its a draft lmao

**Comment by freddierick** [comment]
So far these changes are good

**Comment by fado3669** [comment]
Thanks for the Feedback freddie

**Comment by fado3669** [comment]
closing for rebase kk

**Pull request closed without merging**
