### PR TITLE
Add slash commands to bots

### PR DESCRIPTION
**Pull request by cyanide1x**

### CODE REVIEW

**Comment by Bocon778** [comment]
No

**Comment by DottoXD** [comment]
Yes

**Comment by KnightKing007** [comment]
+1

**Comment by itzJOHv** [comment]
yes

**Comment by danielpmc** [comment]
Already being added on beta bot but will leave this open

**Comment by omxpro** [comment]
> Already being added on beta bot but will leave this open

2 months...

**Comment by yuansheng1549** [comment]
> > Already being added on beta bot but will leave this open
> 
> 2 months...

#230

**Pull request closed without merging**
