### PR TITLE
Updated swear words

### PR DESCRIPTION
**Pull request by BlakeH2208**
If you know what happened in the past, you know why im adding "rape" and different variants of it to the swear list"

### CODE REVIEW

**Comment by jeweetzelfWasTaken** [comment]
Maybe add "rap3" combined with those other variants

**Comment by Darker-Ink** [comment]
This is a terrible PR. The word was removed in [This]([https://github.com/DanBot-Hosting/DanBotHostingStats/commit/f75e8401b8f940555818ab4898c86c430db7dcdf](https://a.disanarchy.xyz/main/mp_/https://github.com/DanBot-Hosting/DanBotHostingStats/commit/f75e8401b8f940555818ab4898c86c430db7dcdf)) merge. The reason is how the system works. Words like "Grape" and other types of words will be blocked. Nobody uses the word enough for it to need to be blocked. You seem to just be but hurt people keep bringing it up. 

There are a TON of words like this as well not just grape. Like "SkyScrapper, Scrape" and others so I don't see the point of this PR.

**Comment by 2MPP** [comment]
🤦

**Comment by itzJOHv** [comment]
> This is a terrible PR. The word was removed in [This](https://github.com/DanBot-Hosting/DanBotHostingStats/commit/f75e8401b8f940555818ab4898c86c430db7dcdf) merge. The reason is how the system works. Words like "Grape" and other types of words will be blocked. Nobody uses the word enough for it to need to be blocked. You seem to just be butt hurt people keep bringing it up.
> 
> There are a TON of words like this as well not just grape. Like "SkyScrapper, Scrape" and others so I don't see the point of this PR.

raw facts

**Pull request closed without merging**
