### PR TITLE
Added back some cheap logo

### PR DESCRIPTION
**Pull request by vinc3nz**
It's anoying to see some image not found image

### CODE REVIEW

**Comment by Darker-Ink** [comment]
why... not... use... DBH's logo...?

**Comment by andrewthemeow** [comment]
> why... not... use... DBH's logo...?

why use DBH logo?

**Comment by Bocon778** [comment]
> It isn't a svg And it never was the DBH Logo I think...

Image converters exist

**Comment by Darker-Ink** [comment]
https://beta.danbot.host/ legit could just use the same image this site
uses dumbass

**Review by migue802 — CHANGES_REQUESTED** [review]
Check this logo from the beta web: https://beta.danbot.host/favicon.ico

**Comment by omxpro** [comment]
I agree

**Comment by vinc3nz** [comment]
I have tried every day since you wrote, but I can't reach the website to get the logo. If you want, you can send me the icon in discord (I'm called Vincenz, I'm the only one with this name in the discord)

**Comment by vinc3nz** [comment]
Closing PR as website got removed

**Pull request closed without merging**
