### PR TITLE
feat: add donator role to correct member

### PR DESCRIPTION
**Pull request by FC5570**
How did nobody notice this.

### CODE REVIEW

**Comment by Microwave-6443** [comment]
the fact that no one noticed that is really sad

**Comment by itzJOHv** [comment]
the only thing i dont understand in this code is why the fuck is userid a GuildMember and is used as a key

**Comment by Microwave-6443** [comment]
> the only thing i dont understand in this code is why the fuck is userid a GuildMember and is used as a key

wait wtf-

**Comment by FC5570** [comment]
> the only thing i dont understand in this code is why the fuck is userid a GuildMember and is used as a key

Fixed

**Comment by danielpmc** [comment]
Solo was the last one to make changes to them 2 lines 
[https://dans.only-fans.club/ZBomeKfo](Screenshot)
[https://dans.only-fans.club/eIXsWzoX](Screenshot 2)

Even the ID is out of date.

**Pull request merged**
