### PR TITLE
Cuwwys Premium Stuff

### PR DESCRIPTION
**Pull request by CurryBoi29**
Dan i did it for you <3

### CODE REVIEW

**Comment by HogunWasTaken** [comment]
like you

**Comment by CurryBoi29** [comment]
Cool i didnt ask. And it doesnt involve you either.
And it isnt useless, its so dan doesnt need to change the files later. He just needs to press 1 button

**Comment by HogunWasTaken** [comment]
shut it

**Comment by CurryBoi29** [comment]
Your the one who replied first. So dont reply to something which doesnt involve you

**Comment by HogunWasTaken** [comment]
wtf is ur username

**Comment by Bocon778** [comment]
> wtf is ur username

You're really trying to start a fight in github comments 💀

**Comment by CurryBoi29** [comment]
> 

Do u mean my github username or my discord username.
As my github username is quite clear, CurryBoi29. Not my fault if you cant read english

**Comment by 2MPP** [comment]
> shut it



> shut it


According to world population studies, approximately 108 billion people have lived on this planet assuming that the average lifespan of all of these people was 25, there has been around 2.7 trillion years of life, if we multiply this by the number of days in a year which is (365) there is a total of 985,500,000,000,000 days of life ( 985.5 trillion days). Not even a single one of these days did anybody ask

**Comment by HogunWasTaken** [comment]
lmfaooooo

**Comment by shurikenxofficial** [comment]
fook u @HogunWasTaken 🖕

**Comment by CurryBoi29** [comment]
> lmfaooooo

now if you want to continue this be sure to send me a message on discord, @1MP#1219

**Comment by Luxxy-GF** [comment]
eeeeeeeeeeeeeee

**Comment by shurikenxofficial** [comment]
fook u all 🖕

**Comment by Luxxy-GF** [comment]
no u

**Comment by shurikenxofficial** [comment]
LUXXY MY GF 😳😳

**Comment by 2MPP** [comment]
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

**Comment by shurikenxofficial** [comment]
> We're no strangers to love
> You know the rules and so do I
> A full commitment's what I'm thinking of
> You wouldn't get this from any other guy
> I just wanna tell you how I'm feeling
> Gotta make you understand
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you
> We've known each other for so long
> Your heart's been aching but you're too shy to say it
> Inside we both know what's been going on
> We know the game and we're gonna play it
> And if you ask me how I'm feeling
> Don't tell me you're too blind to see
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you

FOOK YOU MAN 🖕

**Comment by Luxxy-GF** [comment]
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

**Comment by shurikenxofficial** [comment]
> We're no strangers to love
> You know the rules and so do I
> A full commitment's what I'm thinking of
> You wouldn't get this from any other guy
> I just wanna tell you how I'm feeling
> Gotta make you understand
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you
> We've known each other for so long
> Your heart's been aching but you're too shy to say it
> Inside we both know what's been going on
> We know the game and we're gonna play it
> And if you ask me how I'm feeling
> Don't tell me you're too blind to see
> Never gonna give you up
> Never gonna let you down
> Never gonna run around and desert you
> Never gonna make you cry
> Never gonna say goodbye
> Never gonna tell a lie and hurt you

FOOK YOU TOO MAN 🖕

**Comment by FC5570** [comment]
Shit posting on this repo gets you banned by dan. If you all didn't know already.

**Comment by shurikenxofficial** [comment]
> Shit posting on this repo gets you banned by dan. If you all didn't know already.

WHO ASKED? 🖕

**Comment by 2MPP** [comment]
> Shit posting on this repo gets you banned by dan. If you all didn't know already.

Worth it

**Comment by HogunWasTaken** [comment]
> fook u @HogunWasTaken 🖕

no fook u

**Comment by omxpro** [comment]
> > Shit posting on this repo gets you banned by dan. If you all didn't know already.
> 
> WHO ASKED? 🖕

Your mom did

**Comment by HogunWasTaken** [comment]
deez nuts

**Comment by Robin-Sch** [comment]
w t f

**Comment by andrewthemeow** [comment]
wtf

**Comment by itzJOHv** [comment]
dan will 100% lock this pr after someone else says "wtf" wo im gonna say it

||wtf||

**Comment by omxpro** [comment]
Why do we need this

**Comment by CurryBoi29** [comment]
> Why do we need this

as 2mp said. Its not you who needs this. Its me who needs it.

**Comment by Sliden101** [comment]
Lgtm, but wouldn't dis let curry generate as much premium codes as he wants

**Comment by omxpro** [comment]
> Lgtm, but wouldn't dis let curry generate as much premium codes as he wants

Yes that's why I don't like it, it would be an unfair advantage  above other users

**Comment by 2MPP** [comment]
> > Lgtm, but wouldn't dis let curry generate as much premium codes as he wants
> 
> Yes that's why I don't like it, it would be an unfair advantage above other users

Wdym it’s so curry can do giveaways he not gonna abuse it as dan would know

**Comment by omxpro** [comment]
> > > Lgtm, but wouldn't dis let curry generate as much premium codes as he wants
> > 
> > 
> > Yes that's why I don't like it, it would be an unfair advantage above other users
> 
> Wdym it’s so curry can do giveaways he not gonna abuse it as dan would know

True but why do giveaways  if he does too many giveaways  of prem server yk what can happen?

**Comment by 2MPP** [comment]
> Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr

Because Dans busy most of the time and dosnt respond to dms

**Comment by omxpro** [comment]
> > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> 
> When was the last time Dan replied to your DMs .__.

Around 700 years ago

**Comment by omxpro** [comment]
> > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> 
> Because Dans busy most of the time and dosnt respond to dms oftern

He can dm Dan 10 or 20 days before the game and he can always ask Dan for checking  dms

**Comment by 2MPP** [comment]
> > > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> > 
> > 
> > When was the last time Dan replied to your DMs .__.
> 
> Around 700 years ago

Exactly that’s why this pr

**Comment by 2MPP** [comment]
> > > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> > 
> > 
> > Because Dans busy most of the time and dosnt respond to dms oftern
> 
> He can dm Dan 10 or 20 days before the game and he can always ask Dan for checking dms

That still dosnt work why do u think normaly there is a lot of tickets ect open because Dan dosnt have time to do them

**Comment by KnightKing007** [comment]
> > > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> > 
> > 
> > Because Dans busy most of the time and dosnt respond to dms oftern
> 
> He can dm Dan 10 or 20 days before the game and he can always ask Dan for checking dms



> > > > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> > > 
> > > 
> > > When was the last time Dan replied to your DMs .__.
> > 
> > 
> > Around 700 years ago
> 
> Exactly that’s why this pr



> > > Why not just dm Dan and ask for around 10 - 15 premium codes rather then thus pr
> > 
> > 
> > When was the last time Dan replied to your DMs .__.
> 
> Around 700 years ago

You seemed to have answered your own question "why not DM dan for the codes"

**Comment by Sliden101** [comment]
astolfo is pretty cute ngl

**Comment by CurryBoi29** [comment]
> > 
> 
> Yes that's why I don't like it, it would be an unfair advantage above other users

as ive said around 50000 times. Dan gave me rules on how many times i can use the commands and the amount of giveaways i can host. Like why would i abuse it, im not a dickhead.

And if dan was so worried why would he have given me the option in the first place?

It also isnt unfair, i have -1000 servers so it wouldnt be beneficial to me at all. Like do yall not want giveaways or something? I can perfectly stop doing them if u really want me to.

**Pull request merged**
