### PR TITLE
Fixed up Reaction Roles

### PR DESCRIPTION
**Pull request by Kyro3400**
Now we have reactions roles! (also thanks to z1MP for helping!)

### CODE REVIEW

**Comment by itzJOHv** [comment]
why do you make a separate pr

**Comment by itzJOHv** [comment]
you already made one about this smh

**Comment by Kyro3400** [comment]
> why do you make a separate pr

i worked on them at 2 separate times

**Comment by Kyro3400** [comment]
> you already made one about this smh

ik

**Comment by itzJOHv** [comment]
> > why do you make a separate pr
> 
> i worked on them at 2 separate times

yk what conflict is?

**Pull request merged**
