### PR TITLE
incase anyone forgot there panel email

### PR DESCRIPTION
**Pull request by DinoTheDevOfficial**

### CODE REVIEW

**Comment by HyptexPvP** [comment]
you can use your username to login lmao

**Comment by DinoTheDevOfficial** [comment]
> you can use your username to login lmao

its for the dumbasses ok?

**Review by Xcyth — COMMENTED** [review]
dude you need to use ``` in the dm message and you used "

**Comment by DinoTheDevOfficial** [comment]
@Xcyth fixed

**Comment by Xcyth** [comment]
> @Xcyth fixed

aight

**Comment by Xcyth** [comment]
I do not think you fixed it, use this ` and not '

**Comment by DinoTheDevOfficial** [comment]
@Xcyth @FC5570 fixed fr this time

**Comment by Xcyth** [comment]
there we go

**Comment by FC5570** [comment]
Why do we need an email command if we already have a command which shows the email of a user? Just ask the users to create a new ticket and the bot will show their email

**Comment by DinoTheDevOfficial** [comment]
> Why do we need an email command if we already have a command which shows the email of a user? Just ask the users to create a new ticket and the bot will show their email

I never thought of that I'm retarded

**Comment by freddierick** [comment]
A few small problems:
1. If the user does not have a panel account it will display incorrect infomation
2. It will not display an error if the DM fails to send (user has DMs disabled)

**Comment by Darker-Ink** [comment]
> A few small problems:
> 
> 1. If the user does not have a panel account it will display incorrect information
> 2. It will not display an error if the DM fails to send (user has DMs disabled)

When threads are released they could use that instead of Dming users

**Comment by itzJOHv** [comment]
> > A few small problems:
> > 
> > 1. If the user does not have a panel account it will display incorrect information
> > 2. It will not display an error if the DM fails to send (user has DMs disabled)
> 
> When threads are released they could use that instead of Dming users

agree

**Comment by fado3669** [comment]
i dont recommend using threads instead of dming the user

**Comment by Darker-Ink** [comment]
> i dont recommend using threads instead of dming the user

Why? If it is made private only people with the Admin perm can see it, This way you don't need users to have their dms open

**Comment by Bocon778** [comment]
****

**Pull request closed without merging**
