### PR TITLE
anti-website regex

### PR DESCRIPTION
**Pull request by domin-mnd**
prevent users to have websites in their name

### CODE REVIEW

**Comment by TheCtkHoster** [comment]
why tho

**Comment by Domin-MND** [comment]
> why tho

cuz ye, why not

**Comment by DIBSTERYT** [comment]
We could add this to the DBH rewrite rather than the current Repository, something I'll keep in mind for that bot.

**Comment by Domin-MND** [comment]
We could add this to both rewrite and current bot

**Comment by DIBSTERYT** [comment]
> We could add this to both rewrite and current bot

Always a possibility, will check in on Darker for this.

**Comment by danielpmc** [comment]
almost 1 year ago this was posted. Im going to close it

**Pull request closed without merging**
