### PR TITLE
feat(blWords & snipe attachments): add blacklisted words system & support snipe attachments.

### PR DESCRIPTION
**Pull request by wutv**
This pr adds blacklisted words & supports snipe attachments.

**This has not been tested. Please test this before merging it.**

### CODE REVIEW

**Comment by wutv** [comment]
4096 is the new limit for embed descriptions by the way.

**Review by Darker-Ink — APPROVED** [review]
Looks good 👍  Def should be tested just in case :)

**Comment by Xcyth** [comment]
poggers

**Comment by legendary0001** [comment]
Poggerrs

**Comment by wutv** [comment]
Usage should be something like:
`DBH!staff blwords set frick --action=ban --lowercase=true`,

**Pull request closed without merging**
