### PR TITLE
Make snipe staff only

### PR DESCRIPTION
**Pull request by jeweetzelfWasTaken**
It's against the ToS and why do ppl need it

### CODE REVIEW

**Comment by itzJOHv** [comment]
no

**Comment by itzJOHv** [comment]
i strongly disagree with this pull request

**Comment by omxpro** [comment]
I strongly agree because this IS agaisnt Discord tos

**Comment by Bocon778** [comment]
Bro what how is this against tos?

**Comment by Sliden101** [comment]
this is all i found on the subject https://www.reddit.com/r/discordapp/comments/py5eku/are_bots_that_log_messages_against_tos/

**Comment by Bocon778** [comment]
All I see it "if the bots are storing the messages off-platform (i.e. in their own database), then Discord's developer terms require that (a) the messages be encrypted at rest; and (b) that the messages are not stored for longer than 30 days"

**Comment by Sliden101** [comment]
Well yeah thats what the snipe command is doing isnt it

**Comment by Bocon778** [comment]
Yeah, the messages aren't stored for that long so I imagine its fine

**Comment by Sliden101** [comment]
Still has to be encrypted doe, but idk

**Comment by Microwave-6443** [comment]
If Discord doesn't want us to log messages then they can simple remove the MESSAGE events. Most snipe commands don't store the messages for longer than 5 minutes, and it's kinda stupid to encrypt a message for a snipe command if you intend on people seeing the message.

**Comment by Bocon778** [comment]
> If Discord doesn't want us to log messages then they can simple remove the MESSAGE events. Most snipe commands don't store the messages for longer than 5 minutes, and it's kinda stupid to encrypt a message for a snipe command if you intend on people seeing the message.

This was literally a post I found with a google search I never said it was logical.

**Comment by Sliden101** [comment]
How tf did micro come to the conclusion that discord doesn't want us to log messages

**Comment by Bocon778** [comment]
> How tf did micro come to the conclusion that discord doesn't want us to log messages

Yeah thats what im sayin lmao

**Comment by Sliden101** [comment]
> If Discord doesn't want us to log messages then they can simply remove the MESSAGE events. Most snipe commands don't store the messages for longer than 5 minutes, and it's kinda stupid to encrypt a message for a snipe command if you intend on people seeing the message.

Just encrypt in the db and decrypt later ...

**Comment by danielpmc** [comment]
snipes are just stored in cache at the moment, and deleted after 5minutes.

Personally i see no use of this PR

**Pull request closed without merging**
