### PR TITLE
Fucking console the error Mr. Dipshit

### PR DESCRIPTION
**Pull request by NoahDevelops**
:)

### CODE REVIEW

**Comment by danielpmc** [comment]
ew no

**Comment by NoahDevelops** [comment]
mf you could of saved like 8992374827489298749 minutes by adding that one line

**Comment by danielpmc** [comment]
we legit made it so it doesnt log

**Comment by Jonfirexbox** [comment]
lmao

**Comment by danielpmc** [comment]
f

**Comment by NoahDevelops** [comment]
gay

**Comment by danielpmc** [comment]
submit this again
i cba adding it myself just to check the stupid error

**Pull request closed without merging**
