### PR TITLE
Added the egg that everyone seems to want...

### PR DESCRIPTION
**Pull request by Luxxy-GF**
no need to thank me

### CODE REVIEW

**Comment by andrewthemeow** [comment]
good

**Comment by andrewthemeow** [comment]
very good

**Comment by andrewthemeow** [comment]
FC ur mom is hot ngl

**Comment by RaydanOMGr** [comment]
> FC ur mom is hot ngl

Are you sure about that?

**Comment by RaydanOMGr** [comment]
Hmm

**Comment by jeweetzelfWasTaken** [comment]
Hmm

**Comment by Domin-MND** [comment]
Hmm

**Comment by vinc3nz** [comment]
Hmm

**Comment by andrewthemeow** [comment]
Hmm

**Pull request closed without merging**
