### PR TITLE
Update unproxy.js | Fixing it

### PR DESCRIPTION
**Pull request by WhiteClueGaming**

### CODE REVIEW

**Comment by Sliden101** [comment]
I think it was meant to be off but ok

**Comment by WhiteClueGaming** [comment]
Why was it meant to be off?

**Comment by Sliden101** [comment]
¯\_(ツ)_/¯ I was just told that it was meant to be off by some staff when I tried to use it

**Comment by WhiteClueGaming** [comment]
Ok let's see what the maintainers will do

**Comment by avixityyt** [comment]
> Ok let's see what the maintainers will do

everything that needs to be fixed including proxy command itself ( and anything else that's left ) will be prob pr'ed some time later.

**Comment by itzJOHv** [comment]
dan disabled it on purpose

**Comment by DIBSTERYT** [comment]
Yep, Dan is planning on fixing the unproxy command on the 23rd, for now the unproxy command is disabled.

**Pull request closed without merging**
