### PR TITLE
Rewrite Stuff

### PR DESCRIPTION
**Pull request by Darker-Ink**
This is still a WIP If you have any suggestions leave them down below

## Important Things
- [x] Command Handler, Event Handler and Command Loading/Sub Command Loading
- [x] Creating Users, Linking Users, and Unlinking Users
- [x] User Linked Command and User Premium
- [x] Reset Password
- [x] Premium Commands
- [x] "Donating" Commands
- [x] Server Creation Commands
- [x] Ticket Commands
- [x] Mute and Unmute commands
- [x] Ban and Kick commands
- [x] Reaction Roles
- [x] Suggestion Commands/Suggestions
- [x] Better Help Command
- [ ] Proxy Commands

## Less Important things
- [x] Message Logging
- [x] Server Creation Logging
- [x] Tickets Logging
- [x] User Creation Logging
- [x] More Staff Commands (Warn Commands ETC)
- [x] Report User/Staff Command (Only Admins will be able to see the staff report:+1:)
- [x] Welcome Messages
- [x] Node Info (If the node is up down ETC)
- [ ] Switch to a better HTTP package
- [ ] Using the Cache more than it is (Caching Servers and such)
- [ ] Node Downtime alerts? (Alerts when a Node goes down etc)
- [ ] Some Staff Fixing Commands (ProxyFix ETC)

# Changes

- Updated bot from Discord.JS v12 to v14
- Complete Rewrite on Command Handler and Event Handler
- Change Databases quick.DB to MongoDB
- Redis For Caching
- Better Util and Cleaner Code in General
- License Change from MIT to GNU 3

### CODE REVIEW

**Comment by Darker-Ink** [comment]
*Changed List order to what I think is more important then others

**Comment by Darker-Ink** [comment]
*This Also Changes the License to GNU General Public License v3.0 Package.json does not show that yet

**Comment by Darker-Ink** [comment]
If someone could do the Help command that would be wonderful :+1:

**Comment by Sliden101** [comment]
> If someone could do the Help command that would be wonderful +1

omw

**Comment by Darker-Ink** [comment]
## Not As Important things that need to be done

- [ ] Switch to undici
- [ ] Using the Cache more then it is (Caching Servers and such)


Anything else you might think is important add here (I'll add it to the list) 

If you know how to do these things please help  by doing them :+1:

**Comment by vinc3nz** [comment]
How should the proxy command be made? Should we use the old proxy system (https://github.com/DanBot-Hosting/DanBotHostingStats/blob/master/bot/discord/commands/server/proxy.js) or are any updates updates planned for the proxy backend? Because I would make the cmd on the next days if I have time

**Comment by Darker-Ink** [comment]
> How should the proxy command be made? Should we use the old proxy system (https://github.com/DanBot-Hosting/DanBotHostingStats/blob/master/bot/discord/commands/server/proxy.js) or are any updates planned for the proxy backend? Because I would make the cmd on the next days if I have time

The proxy system there is currently is complete shit, I will work on the proxy system right now though

**Comment by vinc3nz** [comment]
And?

**Comment by itzJOHv** [comment]
>  he's waiting on dan. should've read all the conversation first.

**Comment by danielpmc** [comment]
> > And?
> 
> he's waiting on dan. should've read all the conversation first.

im waiting on darker lmao...

**Comment by itzJOHv** [comment]
> > > And?
> > 
> > he's waiting on dan. should've read all the conversation first.
> 
> im waiting on darker lmao... 

but darker said hes waiting on you lmao

**Comment by danielpmc** [comment]
> > > > And?
> > > 
> > > 
> > > he's waiting on dan. should've read all the conversation first.
> > 
> > 
> > im waiting on darker lmao...
> 
> but darker said hes waiting on you lmao anyways

image

**Comment by TheCtkHoster** [comment]
<@599204289088585738> = egg

**Comment by FC5570** [comment]
How about you stop being cringe

**Comment by danielpmc** [comment]
~~Locked~~

**Comment by WilliamDavidHarrison** [comment]
@Darker-Ink
Add a panel link command.
PR: Darker-Ink/DBH-Rewrite#11

**Comment by dinothedevofficial** [comment]
Suggestion: everytime a suggestion is posted the DBH bot will follow up with a prewrote message basically saying the rules, ect. As most people don't read guidelines kinda like a discord.js bot thing

**Comment by dinothedevofficial** [comment]
> @Darker-Ink Add a panel link command. PR: [Darker-Ink#11](https://github.com/Darker-Ink/DBH-Rewrite/pull/11)

I'm pretty sure people can put 2 and 2 together if not humanity is screwed

**Comment by dinothedevofficial** [comment]
Description: Add `.toLowerCase()` to message.content
File: `src/commands/server/delete.js`

Type: Quality Of Life

**Comment by Darker-Ink** [comment]
> Description: Add `.toLowerCase()` to message.content File: `src/commands/server/delete.js`
> 
> Type: Quality Of Life

oop been so long I forgot I do buttons iirc so :+1:

**Comment by WilliamDavidHarrison** [comment]
RIP

**Pull request closed without merging**
