### PR TITLE
Blacklisting channels for commands.

### PR DESCRIPTION
**Pull request by DIBSTERYT**
I saw some people mention in chat of removing the ability to run anywhere else but command channels, I think this pull request solves that, idk I'm kinda a noob, so if you see anything wrong just point it out/fix it.

### CODE REVIEW

**Comment by omxpro** [comment]
^^

**Comment by itzJOHv** [comment]
discord snowflakes are strings smh

**Comment by itzJOHv** [comment]
* twitter snowflakes

**Comment by itzJOHv** [comment]
@DIBSTERYT fix this

**Comment by Darker-Ink** [comment]
https://github.com/DanBot-Hosting/DanBotHostingStats/blob/master/bot/discord/events/message.js#L107

**Pull request closed without merging**
