### PR TITLE
Allowing DIBSTER to process donations.

### PR DESCRIPTION
**Pull request by DEV-DIBSTER1**
I'd be able to process donations when Sarah and Dan are unavailable, but I can only do it with ticket proof.

If you disagree kindly comment it.

### CODE REVIEW

**Comment by avixityyt** [comment]
agreed.

> would be cool if i could , as i have not much to do atm , same concept as dib mentioned.

**Review by yuansheng1549 — APPROVED** [review]

**Review by lolollllo — APPROVED** [review]

**Comment by jeweetzelfWasTaken** [comment]
I don't fully agree on this, yes, it always takes some time before Dan or Sarah check DBH's PayPal, but it is kinda easy to fake a payment if you don't have access to DBH's PayPal. Just wanted to point that out.

**Comment by Darker-Ink** [comment]
> I don't fully agree on this, yes, it always takes some time before Dan or Sarah check DBH's PayPal, but it is kinda easy to fake a payment if you don't have access to DBH's PayPal. Just wanted to point that out.

I completely agree with this.

**Comment by avixityyt** [comment]
> > I don't fully agree on this, yes, it always takes some time before Dan or Sarah check DBH's PayPal, but it is kinda easy to fake a payment if you don't have access to DBH's PayPal. Just wanted to point that out.
> 
> I completely agree with this.

i agree with this that darker agrees with that that jeweetzelf doesn't agree fully.

**Comment by jeweetzelfWasTaken** [comment]
> > > I don't fully agree on this, yes, it always takes some time before Dan or Sarah check DBH's PayPal, but it is kinda easy to fake a payment if you don't have access to DBH's PayPal. Just wanted to point that out.
> > 
> > 
> > I completely agree with this.
> 
> i agree with this that darker agrees with that that jeweetzelf doesn't agree fully.

Nice.

**Comment by DEV-DIBSTER1** [comment]
> I don't fully agree on this, yes, it always takes some time before Dan or Sarah check DBH's PayPal, but it is kinda easy to fake a payment if you don't have access to DBH's PayPal. Just wanted to point that out.

Fair response which is understandable, it seems some of the fellow staff members agree with this, I will close edit it out and close my PR in a couple hours.

**Comment by Bocon778** [comment]
I disagree, it’s not fair just to give one staff member a permission mods don’t even have.

**Comment by DEV-DIBSTER1** [comment]
> I disagree, it’s not fair just to give one staff member a permission mods don’t even have.

Yeah, I'm editing out my commits and closing the PR.

**Review by itzJOHv — COMMENTED** [review]
why tho

**Pull request closed without merging**
