### PR TITLE
Remove unnecessary styling in ticket commands

### PR DESCRIPTION
**Pull request by FC5570**
- #141 #144

### CODE REVIEW

**Comment by Darker-Ink** [comment]
omg I love this pr FC ily <3

**Comment by itzJOHv** [comment]
the best pr i've ever seen. take a heart <3

**Comment by Darker-Ink** [comment]
> the best pr i've ever seen. take a heart <3

fr I hated the random bolded things

**Comment by itzJOHv** [comment]
> > the best pr i've ever seen. take a heart <3
> 
> fr I hated the random bolded things

yea me too lmao

who added them ~~should not deserve a life~~

**Comment by omxpro** [comment]
Best pr fr

**Comment by freddierick** [comment]
Are there anymore files that still use the random bold characters (have you updated every file)?

**Comment by freddierick** [comment]
Are there anymore files that still use the random bold characters (have you updated every file)?

**Comment by FC5570** [comment]
Ofcourse. I have updated all the files. I don't think there's any left.

**Comment by freddierick** [comment]
Ultimately this is up to Dan

**Pull request merged**
